import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlayer,scopedPlayer} from '../apps/tts/service.js';
const config={url:'http://localhost:9883',speed:1,volume:1,seed:42};
const parts=['第一段','第二段','第三段'].map(text=>({type:'narration',text}));
function rig(){const sent=[];let fail=true;const audio={volume:1,pause(){},load(){},removeAttribute(){},async play(){queueMicrotask(()=>this.onended?.());}};const player=createPlayer({audio,check:async()=>{},request:async(url,init)=>{const body=JSON.parse(init.body);sent.push(body);if(body.text==='第二段'&&fail)throw Error('临时失败');return new Response(new Blob(['0'.repeat(60)],{type:'audio/wav'}));},urls:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}}});return {player,sent,recover:()=>fail=false};}
test('retry only regenerates failed segment then continues with original config',async()=>{const {player,sent,recover}=rig();const settings={...config};await player.play(parts,'floor-1',settings);assert.equal(player.snapshot().canRetry,true);assert.match(player.snapshot().message,/2\/3/);settings.speed=1.2;recover();await player.retry();assert.deepEqual(sent.map(x=>x.text),['第一段','第二段','第二段','第三段']);assert.ok(sent.every(x=>x.speed===1));assert.equal(player.snapshot().canRetry,false);assert.equal(player.snapshot().message,'朗读完成');});
test('another floor cannot retry and stop discards failed queue',async()=>{const {player,sent,recover}=rig();await player.play(parts,'one',config);recover();await scopedPlayer(player,'two').retry();assert.equal(sent.length,2);player.stop();await player.retry();assert.equal(sent.length,2);assert.equal(player.snapshot().canRetry,false);});
test('repeated failure retains position and simultaneous retry cannot submit twice',async()=>{const {player,sent,recover}=rig();await player.play(parts,'one',config);await player.retry();assert.deepEqual(sent.map(x=>x.text),['第一段','第二段','第二段']);recover();await Promise.all([player.retry(),player.retry()]);assert.deepEqual(sent.map(x=>x.text),['第一段','第二段','第二段','第二段','第三段']);});
