import test from 'node:test';
import assert from 'node:assert/strict';
import {createPlayer} from '../apps/tts/service.js';
import {createLibrary} from '../apps/tts/library.js';
import {previewSections,planSpeech} from '../apps/tts/dialogue.js';
const config={provider:'azuma',url:'http://localhost:9883',speed:1,volume:1,seed:42,cloud:{mimoKey:'must-not-save'}};
function rig(){const library=createLibrary(),calls=[];let fail=false;const audio={volume:1,pause(){},load(){},removeAttribute(){},async play(){queueMicrotask(()=>this.onended?.());}};const player=createPlayer({audio,library,check:async()=>{},request:async(url,init)=>{calls.push(JSON.parse(init.body).text);if(fail)throw Error('失败');return new Response(new Blob(['0'.repeat(60)],{type:'audio/wav'}));},urls:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}}});return {library,calls,player,setFail:v=>fail=v};}
test('preview exposes actual split units and deselection preserves stable segment identity',()=>{const sections=previewSections('甲。\n“乙。”\n'+'丙'.repeat(300));assert.ok(sections.every(x=>x.text.length<=220));const all=planSpeech(sections,config);sections[0].enabled=false;const selected=planSpeech(sections,config);assert.equal(selected.length,all.length-1);assert.equal(selected[0].segmentId,all[1].segmentId);});
test('generate only saves each selected segment without secrets, replay makes no request',async()=>{const {library,calls,player}=rig();const sections=previewSections('甲。\n乙。');sections[0].enabled=false;await player.play(sections,'chat:1',config,{generateOnly:true});const saved=await library.list('chat:1');assert.equal(saved.length,1);assert.equal(saved[0].sectionNumber,2);assert.ok(saved[0].blob instanceof Blob);assert.ok(!JSON.stringify(saved).includes('must-not-save'));await player.replay(saved[0]);assert.deepEqual(calls,['乙。']);assert.equal((await library.list('chat:2')).length,0);});
test('single regeneration replaces only selected audio and failure retains old recording',async()=>{const {library,player,setFail}=rig();await player.play(previewSections('甲。\n乙。'),'chat:1',config,{generateOnly:true});const old=await library.list('chat:1');setFail(true);await player.regenerate(old[0],config);assert.equal((await library.list('chat:1'))[0].blob,old[0].blob);setFail(false);await player.retry();const saved=await library.list('chat:1');assert.equal(saved.length,2);assert.notEqual(saved.find(x=>x.id===old[0].id).blob,old[0].blob);assert.equal(saved.find(x=>x.id===old[1].id).blob,old[1].blob);await library.remove(old[0].id,'chat:1');assert.equal((await library.list('chat:1')).length,1);});
