import test from 'node:test';import assert from 'node:assert/strict';
import {collectWorldbooks,resolvedBookNames,sourceSettings,saveSourceSettings,worldbookChoices} from '../apps/worldbook-sources.js';
import {collectStatusSources} from '../apps/status/sources.js';import {generateStatus} from '../apps/status/generator.js';import {collectMapSources,readMapSources} from '../apps/map/src/adapters/sources.js';import {collectSources} from '../apps/organizations/ai.js';
function fixture(){let revision='first';const calls=[];const ctx={id:'chat',characterId:0,characters:[{avatar:'card.png',data:{name:'角色',description:'角色背景',extensions:{world:'bound'}}}],chatMetadata:{world_info:'chatbook',variables:{}},chat:[{mes:'当前剧情',name:'角色'}],extensionSettings:{},getCurrentChatId(){return this.id;},getRequestHeaders:()=>({}),saveMetadata:async()=>{},saveSettingsDebounced(){}};const wi={selected_world_info:['global','bound'],world_names:['bound','extra','chatbook','global','inactive'],world_info:{charLore:[{name:'card',extraBooks:['extra']}]}};const readBook=async name=>{calls.push(name);return {entries:{one:{content:name+':'+revision,key:['unmatched'],constant:false,probability:0,useProbability:true},two:{content:'disabled',disable:true},three:{content:'disabled-embedded',enabled:false}}};};wi.loadWorldInfo=readBook;return {ctx,wi,calls,rev:v=>revision=v,options:{loadWorldInfo:async()=>wi,readBook}};}
const adapters={status:async(h,c,o)=>collectStatusSources(h.ctx,c,o),map:async(h,c,o)=>(await collectMapSources(h.ctx,h.wi,{...c,...o})).source,organizations:(h,c,o)=>collectSources(h.ctx,c,o)};
test('three applications read the same enabled selected material irrespective of activation strategy',async()=>{for(const [app,read]of Object.entries(adapters)){const h=fixture(),result=await read(h,{includeCharacter:true,selectedBooks:['global','bound','extra']},h.options),text=JSON.stringify(result);assert.deepEqual(new Set(h.calls),new Set(['bound','extra','global']),app);assert.equal(h.calls.length,3);assert.ok(text.includes('global:first'));assert.ok(!text.includes('disabled'));assert.ok(!text.includes('inactive'));}});
test('three applications master switch bypasses worldbook interfaces and preserves character content',async()=>{for(const [app,read]of Object.entries(adapters)){const h=fixture(),options={loadWorldInfo:()=>{throw Error('no catalogue');},readBook:()=>{throw Error('no body');}},result=await read(h,{includeCharacter:true,readWorldbooks:false,selectedBooks:['global']},options);assert.ok(JSON.stringify(result).includes('角色背景'),app);assert.equal(h.calls.length,0);}});
test('legacy status and map selections migrate without auto-selecting the entire library',async()=>{const h=fixture(),choices=await worldbookChoices(h.ctx,h.options);assert.deepEqual(new Set(resolvedBookNames({legacyBindings:true,includeGlobalBooks:true,extraBooks:['extra']},choices)),new Set(['extra','chatbook','global','bound']));assert.deepEqual(resolvedBookNames({legacyBindings:true,includeGlobal:false},choices),['chatbook']);assert.deepEqual(resolvedBookNames({legacyBindings:true,includeGlobalBooks:true,selectedBooks:[]},choices),[]);});
test('all adapters reread after edits and preserve large worldbooks without a source cap',async()=>{for(const read of Object.values(adapters)){const h=fixture(),config={includeCharacter:true,selectedBooks:['global','bound','extra'],maxSourceChars:1};const first=await read(h,config,h.options);h.rev('资料'.repeat(150000)+'末尾');const second=await read(h,config,h.options);assert.ok(JSON.stringify(first).includes('global:first'));assert.ok(!JSON.stringify(second).includes('global:first'));assert.ok(JSON.stringify(second).includes('资料'.repeat(150000)+'末尾'));assert.equal(h.calls.length,6);}});
test('worldbook selections are isolated across application, character and chat reads without replacing legacy settings',()=>{const h=fixture();h.ctx.extensionSettings.world_status_hud_v1={includeGlobalBooks:true,extraBooks:'extra'};const before=structuredClone(h.ctx.extensionSettings.world_status_hud_v1);saveSourceSettings(h.ctx,'status',{includeCharacter:true,readWorldbooks:false,selectedBooks:['global']});assert.equal(sourceSettings(h.ctx,'status').readWorldbooks,false);assert.equal(sourceSettings(h.ctx,'map').readWorldbooks,true);h.ctx.characters.push({avatar:'other.png'});h.ctx.characterId=1;assert.equal(sourceSettings(h.ctx,'status').readWorldbooks,true);h.ctx.characterId=0;assert.deepEqual(sourceSettings(h.ctx,'status').selectedBooks,['global']);assert.deepEqual(h.ctx.extensionSettings.world_status_hud_v1,before);});
test('map production adapter always uses a fresh no-store request rather than the injected module cache',async()=>{const h=fixture();h.wi.loadWorldInfo=()=>{throw Error('cached reader must not be used');};let n=0;const options={includeCharacter:false,selectedBooks:['global'],loadWorldInfo:async()=>h.wi,fetcher:async(route,opts)=>{assert.equal(route,'/api/worldinfo/get');assert.equal(opts.cache,'no-store');return {ok:true,json:async()=>({entries:{a:{content:'revision-'+(++n)}}})};}};assert.ok(JSON.stringify(await readMapSources(h.ctx,options)).includes('revision-1'));assert.ok(JSON.stringify(await readMapSources(h.ctx,options)).includes('revision-2'));});
test('status fill/replace/update requests reread worlds and ignore the retired source cap',async()=>{const previous=globalThis.window;try{for(const mode of ['fill','replace','update']){const h=fixture();h.ctx.chatMetadata.variables.状态栏=JSON.stringify({版本:1,项目:{世界:{地点:'旧地点'}}});let request;h.ctx.generateRaw=async r=>{request=r;throw Error('request captured');};globalThis.window={SillyTavern:{getContext:()=>h.ctx}};const options={...h.options,loadVariables:async()=>({setLocalVariable(){}})},config={mode,api:{baseUrl:'',timeoutMs:5000,maxTokens:1024},includeCharacter:true,selectedBooks:['global','bound','extra'],maxSourceChars:1};h.rev('正文'.repeat(110000)+'末尾');const result=await generateStatus(config,undefined,options);assert.equal(result.message,'request captured');assert.ok(request.prompt.includes('正文'.repeat(110000)+'末尾'));h.rev('new revision');await generateStatus(config,undefined,options);assert.ok(request.prompt.includes('new revision'));assert.ok(!request.prompt.includes('正文'.repeat(20)));assert.equal(h.calls.length,6);}}finally{globalThis.window=previous;}});
test('status changes of chat while reading refuse late source material before model invocation',async()=>{const h=fixture(),previous=globalThis.window;let modelCalls=0;h.ctx.generateRaw=async()=>{modelCalls++;};globalThis.window={SillyTavern:{getContext:()=>h.ctx}};try{const result=await generateStatus({mode:'fill',api:{timeoutMs:5000},includeCharacter:true},undefined,{...h.options,loadVariables:async()=>({setLocalVariable(){}}),readBook:async()=>{h.ctx.id='other';return {entries:{}};}});assert.equal(result.ok,false);assert.match(result.message,/聊天已切换/);assert.equal(modelCalls,0);}finally{globalThis.window=previous;}});

test('migrated chat bindings stay isolated across chats of the same role, even when the old book remains globally enabled',async()=>{
 for(const app of ['status','map']){const h=fixture(),legacy={legacyBindings:true,includeGlobalBooks:false,includeGlobal:false};h.ctx.chatMetadata.world_info='chatA';h.wi.selected_world_info.push('chatA');
 const initial=sourceSettings(h.ctx,app,legacy);initial.selectedBooks=resolvedBookNames(initial,await worldbookChoices(h.ctx,h.options));saveSourceSettings(h.ctx,app,initial);
 const metadataA=h.ctx.chatMetadata;h.ctx.id='chatB';h.ctx.chatMetadata={world_info:'chatB',variables:{}};const next=sourceSettings(h.ctx,app,legacy);assert.equal(next.selectedBooks,null);h.calls.length=0;await adapters[app](h,next,h.options);assert.ok(h.calls.includes('chatB'));assert.ok(!h.calls.includes('chatA'));
 next.selectedBooks=resolvedBookNames(next,await worldbookChoices(h.ctx,h.options));saveSourceSettings(h.ctx,app,next);h.wi.selected_world_info=h.wi.selected_world_info.filter(n=>n!=='chatA');h.calls.length=0;await adapters[app](h,sourceSettings(h.ctx,app,legacy),h.options);assert.ok(h.calls.includes('chatB'));assert.ok(!h.calls.includes('chatA'));
 h.ctx.id='chat';h.ctx.chatMetadata=metadataA;assert.deepEqual(sourceSettings(h.ctx,app,legacy).selectedBooks,['chatA']);
 }
});
test('missing stable chat identity never persists selected books at role scope',()=>{const h=fixture();delete h.ctx.getCurrentChatId;saveSourceSettings(h.ctx,'map',{readWorldbooks:true,selectedBooks:['chatA']});h.ctx.chatMetadata={world_info:'chatB'};assert.equal(sourceSettings(h.ctx,'map').selectedBooks,null);});

test('status and map read bound and additional books only when selected, independent of character text',async()=>{
 for(const app of ['status','map']){const h=fixture(),read=adapters[app];let result=await read(h,{includeCharacter:true,selectedBooks:[]},h.options);assert.deepEqual(h.calls,[],app);assert.ok(JSON.stringify(result).includes('角色背景'));assert.deepEqual(result.世界书,[]);
 result=await read(h,{includeCharacter:true,selectedBooks:['bound']},h.options);assert.deepEqual(h.calls,['bound']);assert.deepEqual(result.世界书.map(b=>b.名称),['bound']);
 h.calls.length=0;result=await read(h,{includeCharacter:false,selectedBooks:['bound','extra']},h.options);assert.deepEqual(h.calls,['bound','extra']);assert.deepEqual(result.角色卡,{});
 h.calls.length=0;result=await read(h,{includeCharacter:true,selectedBooks:[]},h.options);assert.deepEqual(h.calls,[]);assert.deepEqual(result.世界书,[]);
 }
});
test('embedded books remain selectable without being automatically sent with character data',async()=>{
 for(const app of ['status','map']){const h=fixture();delete h.ctx.characters[0].data.extensions.world;h.ctx.characters[0].name='角色';h.ctx.characters[0].data.character_book={name:'内嵌书',entries:[{content:'EMBEDDED_MARKER',enabled:true},{content:'disabled',enabled:false}]};const embedded=(await worldbookChoices(h.ctx,h.options)).find(b=>b.data);
 let result=await adapters[app](h,{includeCharacter:true,selectedBooks:[]},h.options);assert.deepEqual(result.世界书,[]);assert.ok(!JSON.stringify(result).includes('EMBEDDED_MARKER'));
 result=await adapters[app](h,{includeCharacter:false,selectedBooks:[embedded.name]},h.options);assert.deepEqual(result.角色卡,{});assert.equal(result.世界书.length,1);assert.equal(result.世界书[0].条目[0].内容,'EMBEDDED_MARKER');assert.equal(h.calls.length,0);
 }
});
