export const BASE_VOICE='一位二十多岁的年轻成年女性，声音清亮柔和，音高中等偏高，发声轻松自然。普通话清晰，咬字轻巧，像与熟悉的人面对面聊天。语速适中，句间停顿自然，尾音收束干净。整体亲切，带少许俏皮感，避免刻意挤压的尖细嗓音和夸张播音腔。';
export const isCloud=config=>['mimo-direct','volcengine'].includes(config.provider);
export function validateCloud(config){const c=config.cloud??{};if(config.provider==='mimo-direct'&&!c.mimoKey?.trim())throw Error('请填写 MiMo API Key');if(config.provider==='volcengine'){if(!c.volcAppId?.trim()||!c.volcToken?.trim())throw Error('请填写火山 App ID 和 Access Token');if(!c.speaker?.trim()||!c.resource?.trim())throw Error('请填写火山音色 ID 和资源 ID');}return true;}
export function cloudRequest(part,config){validateCloud(config);const c=config.cloud;const headers={'Content-Type':'application/json'};
 if(config.provider==='mimo-direct')return {url:'https://api.xiaomimimo.com/v1/chat/completions',headers:{...headers,Authorization:'Bearer '+c.mimoKey.trim()},body:{model:'mimo-v2.5-tts-voicedesign',messages:[{role:'user',content:(config.voicePrompt.trim()||BASE_VOICE)+'\n本次情绪与演绎：'+(part.emotion||'自然亲切')},{role:'assistant',content:part.text}],audio:{format:'wav',optimize_text_preview:false},stream:false}};
 const emotion=part.volcEmotion?.trim();return {url:'https://openspeech.bytedance.com/api/v3/tts/unidirectional/sse',headers:{...headers,'X-Api-App-Key':c.volcAppId.trim(),'X-Api-Access-Key':c.volcToken.trim(),'X-Api-Resource-Id':c.resource.trim(),'X-Api-Request-Id':crypto.randomUUID()},body:{user:{uid:'amin-os'},req_params:{text:part.text,speaker:c.speaker.trim(),audio_params:{format:'mp3',sample_rate:24000,speech_rate:Math.round((part.speed-1)*100),...(emotion?{emotion}: {})},additions:JSON.stringify({disable_markdown_filter:true})}}};
}
function decode(value){if(typeof value!=='string'||!value)throw Error('接口未返回音频');try{return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}catch{throw Error('音频编码无效');}}
export function parseVolc(text){const audio=[];for(const line of text.split(/\r?\n/)){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(!raw||raw==='[DONE]')continue;let event;try{event=JSON.parse(raw);}catch{throw Error('火山返回无效事件');}if(![0,20000000].includes(event.code??0))throw Error('火山合成失败，错误码 '+event.code);if(event.data)audio.push(decode(event.data));}if(!audio.length)throw Error('火山未返回音频，请检查音色与资源权限');return new Blob(audio,{type:'audio/mpeg'});}
export async function generateCloud(part,config,signal,fetchImpl=fetch){const req=cloudRequest(part,config);let response;try{response=await fetchImpl(req.url,{method:'POST',headers:req.headers,body:JSON.stringify(req.body),credentials:'omit',redirect:'error',signal:AbortSignal.any([signal,AbortSignal.timeout(180000)])});}catch(e){if(signal.aborted||e.name==='TimeoutError')throw e;throw Error('云端连接失败，请检查网络或接口跨域支持');}if(!response.ok)throw Error('语音 API 返回 HTTP '+response.status+'，请检查密钥、余额和音色权限');const blob=config.provider==='mimo-direct'?new Blob([decode((await response.json()).choices?.[0]?.message?.audio?.data)],{type:'audio/wav'}):parseVolc(await response.text());return new Response(blob);}
