import {getPlayer,scopedPlayer,settings,saveSettings,health} from './service.js';
export function mount(target,{readMessage=null,source='app'}={}){
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};const root=el('div');root.className='amin-page amin-tts';const intro=el('p','东雪莲 · Azuma Bert-VITS2 2.3 · 本地中文朗读');intro.className='amin-context';root.append(intro);
 const label=el('label','待朗读文字'),text=el('textarea');text.rows=7;text.style.width='100%';let rendered=readMessage?.()??null;text.value=rendered??'晚上好，今天过得怎么样？';label.append(text);root.append(label);if(readMessage)root.append(el('p','只朗读这一层正则处理后的可见正文，不连续朗读其他楼层。'));
 const player=scopedPlayer(getPlayer(),source),bar=el('div');bar.className='amin-toolbar';const button=(title,fn)=>{const b=el('button',title);b.type='button';b.onclick=fn;bar.append(b);return b;};
 const play=button(readMessage?'朗读本层':'播放',()=>{if(readMessage){const latest=readMessage();if(latest!==rendered){rendered=latest;text.value=latest;}}player.play(text.value,source);});play.className='amin-primary';const pause=button('暂停',()=>player.pause()),resume=button('继续',()=>player.resume());const stop=button('停止',()=>player.stop());root.append(bar);
 const status=el('p');status.setAttribute('role','status');root.append(status);const off=player.subscribe(s=>{status.textContent=s.message;pause.disabled=s.phase!=='playing';resume.disabled=s.phase!=='paused';stop.disabled=!['loading','playing','paused'].includes(s.phase);});
 const detail=el('details'),summary=el('summary','语音设置');detail.append(summary);const config=settings(),inputs={};for(const [key,title,type,min,max,step]of [['url','本机服务地址','url'],['speed','语速','number',.7,1.3,.05],['volume','音量','number',0,1,.1],['seed','种子（保持音色表现一致）','number',0,4294967295,1]]){const row=el('label',title),input=el('input');input.type=type;input.value=config[key];if(min!==undefined){input.min=min;input.max=max;input.step=step;}row.style.display='block';row.append(input);detail.append(row);inputs[key]=input;}
 const save=el('button','保存设置');save.type='button';save.onclick=()=>{try{saveSettings(Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value])));status.textContent='设置已保存';}catch(e){status.textContent=e.message;}};const test=el('button','检查连接');test.type='button';test.onclick=async()=>{test.disabled=true;try{await health({...settings(),url:inputs.url.value});status.textContent='已连接：东雪莲 / G_18200 / Bert-VITS2 2.3';}catch(e){status.textContent=e.message;}finally{test.disabled=false;}};detail.append(save,test,el('p','请先运行模型目录中的“启动试听.cmd”。只在本机合成，不发送至聊天模型。长文本自动分段；播放前可编辑文字。'));root.append(detail);target.append(root);return {dispose(){off();root.remove();},open(){}};
}
