import {getPlayer,scopedPlayer,settings,saveSettings,health} from './service.js';
import {classify,profiles} from './dialogue.js';
export function mount(target,{readMessage=null,source='app'}={}){
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 const root=el('div');root.className='amin-page amin-tts';root.append(el('p','本层语音 · 对话与旁白可分别调整参数'));
 const text=el('textarea');text.rows=6;text.style.width='100%';let rendered=readMessage?.()??null;text.value=rendered??'她轻轻敲门，说：“晚上好，今天过得怎么样？”';root.append(text);if(readMessage)root.append(el('p','只朗读本层正则处理后的正文，不连读其他楼层。'));
 const cfg=settings(),range=el('select');for(const [value,title]of [['all','全部（原文顺序）'],['dialogue','仅对话'],['narration','仅旁白／其他正文']]){const o=el('option',title);o.value=value;range.append(o);}range.value=cfg.range;const rangeLabel=el('label','朗读范围 ');rangeLabel.append(range);root.append(rangeLabel);
 const detail=el('details');detail.append(el('summary','语音与识别设置'));const input=(parent,title,value,type='number',min,max,step)=>{const label=el('label',title+' '),field=el('input');field.type=type;field.value=value;if(min!==undefined){field.min=min;field.max=max;field.step=step;}label.style.display='block';label.append(field);parent.append(label);return field;};
 const provider=el('select');for(const [value,title]of [['azuma','本地 Bert-VITS2 东雪莲'],['mimo','MiMo → 本地 DXL1 RVC']]){const o=el('option',title);o.value=value;provider.append(o);}provider.value=cfg.provider;const providerLabel=el('label','语音引擎 ');providerLabel.append(provider);detail.append(providerLabel);
 const url=input(detail,'本机服务地址',cfg.url,'url'),seed=input(detail,'种子',cfg.seed,'number',0,4294967295,1),fields={},p=profiles(cfg);
 provider.onchange=()=>{url.value=provider.value==='mimo'?'http://127.0.0.1:9884':'http://127.0.0.1:9883';};
 const ratio=el('select');for(const v of [.5,.75]){const o=el('option',String(v));o.value=v;ratio.append(o);}ratio.value=cfg.ratio;const ratioLabel=el('label','DXL1 索引比例 ');ratioLabel.append(ratio);detail.append(ratioLabel);const voicePrompt=el('textarea');voicePrompt.rows=4;voicePrompt.maxLength=2000;voicePrompt.value=cfg.voicePrompt;voicePrompt.placeholder='留空使用试听台已选基础声线';const voiceLabel=el('label','MiMo 基础声线 ');voiceLabel.append(voicePrompt);detail.append(voiceLabel,el('p','MiMo 会将待朗读正文发送至官方 API 并产生调用费用；密钥只在本地 9884 试听页设置。DXL1 在本机转换，角色与原作者未确认。语速由播放器调整，情绪交给 MiMo。')); 
 for(const [type,title]of [['dialogue','对话'],['narration','旁白／其他正文']]){const box=el('fieldset');box.append(el('legend',title));fields[type]={speed:input(box,'语速（0.7～1.3）',p[type].speed,'number',.7,1.3,.05),volume:input(box,'音量（0～100%）',Math.round(p[type].volume*100),'number',0,100,1),pauseMs:input(box,'段后停顿（毫秒）',p[type].pauseMs,'number',0,5000,50)};const emotion=el('select');for(const v of ['日常','温柔','开心','小吐槽']){const o=el('option',v);o.value=v;emotion.append(o);}emotion.value=p[type].emotion;fields[type].emotion=emotion;const lab=el('label','MiMo 情绪 ');lab.append(emotion);box.append(lab);detail.append(box);}
 const quotes=el('textarea');quotes.rows=4;quotes.value=cfg.quotes;const qlabel=el('label','对话引号规则（每行一对）');qlabel.style.display='block';qlabel.append(quotes);detail.append(qlabel,el('p','引号内视为对话，其余为旁白。引号不完整时保留为旁白；引用、强调可在下方手动纠正。'));
 const collect=()=>({...cfg,provider:provider.value,ratio:Number(ratio.value),voicePrompt:voicePrompt.value,url:url.value,seed:Number(seed.value),range:range.value,quotes:quotes.value,profiles:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,{speed:Number(v.speed.value),volume:Number(v.volume.value)/100,pauseMs:Number(v.pauseMs.value),emotion:v.emotion.value}]))});
 const status=el('p');status.setAttribute('role','status');const player=scopedPlayer(getPlayer(),source),bar=el('div');bar.className='amin-toolbar';const button=(parent,title,fn)=>{const b=el('button',title);b.type='button';b.onclick=fn;parent.append(b);return b;};
 let sections=[],signature='';const preview=el('details');preview.open=true;preview.append(el('summary','分类预览（可修改分类）'));const rows=el('div');preview.append(rows);
 function analyze(){const next=text.value+'\0'+quotes.value;if(next===signature)return;const parsed=classify(text.value,quotes.value);sections=parsed;signature=next;rows.replaceChildren();for(const section of sections){if(!section.text.trim())continue;const row=el('div');row.className='amin-card';const select=el('select');select.setAttribute('aria-label','段落分类');for(const [value,title]of [['dialogue','对话'],['narration','旁白／其他正文']]){const o=el('option',title);o.value=value;select.append(o);}select.value=section.type;select.onchange=()=>section.type=select.value;row.append(select,el('p',section.text));rows.append(row);}}
 text.onchange=quotes.onchange=()=>{try{analyze();}catch(e){status.textContent=e.message;}};
 button(detail,'保存设置',()=>{try{saveSettings(collect());analyze();status.textContent='设置已保存';}catch(e){status.textContent=e.message;}});
 button(detail,'检查连接',async()=>{try{await health(collect());status.textContent=provider.value==='mimo'?'已连接 MiMo → DXL1':'东雪莲服务已连接';}catch(e){status.textContent=e.message;}});
 const play=button(bar,readMessage?'朗读本层':'播放',()=>{try{if(readMessage){const latest=readMessage();if(latest!==rendered){rendered=latest;text.value=latest;}}const config=collect();saveSettings(config);analyze();player.play(sections.map(s=>({...s})),config);}catch(e){status.textContent=e.message;}});play.className='amin-primary';
 const pause=button(bar,'暂停',()=>player.pause()),resume=button(bar,'继续',()=>player.resume()),stop=button(bar,'停止',()=>player.stop());
 root.append(bar,status,detail,preview);const off=player.subscribe(s=>{status.textContent=s.message;pause.disabled=s.phase!=='playing';resume.disabled=s.phase!=='paused';stop.disabled=!['loading','playing','paused','waiting'].includes(s.phase);});
 target.append(root);analyze();return {dispose(){off();root.remove();},open(){}};
}
