import {EMOTIONS,speedMax} from './emotions.js';
import {launchTarget,waitForService} from './launcher.js';
import {isCloud,BASE_VOICE} from './cloud.js';
import {getPlayer,scopedPlayer,settings,saveSettings,health} from './service.js';
import {classify,profiles} from './dialogue.js';
export function mount(target,{readMessage=null,source='app'}={}){
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 const root=el('div');root.className='amin-page amin-tts';root.append(el('p','本层语音 · 对话与旁白可分别调整参数'));
 const text=el('textarea');text.rows=6;text.style.width='100%';let rendered=readMessage?.()??null;text.value=rendered??'她轻轻敲门，说：“晚上好，今天过得怎么样？”';root.append(text);if(readMessage)root.append(el('p','只朗读本层正则处理后的正文，不连读其他楼层。'));
 const cfg=settings(),range=el('select');for(const [value,title]of [['all','全部（原文顺序）'],['dialogue','仅对话'],['narration','仅旁白／其他正文']]){const o=el('option',title);o.value=value;range.append(o);}range.value=cfg.range;const rangeLabel=el('label','朗读范围 ');rangeLabel.append(range);root.append(rangeLabel);
 const detail=el('details');detail.append(el('summary','语音与识别设置'));const input=(parent,title,value,type='number',min,max,step)=>{const label=el('label',title+' '),field=el('input');field.type=type;field.value=value;if(min!==undefined){field.min=min;field.max=max;field.step=step;}label.style.display='block';label.append(field);parent.append(label);return field;};
 const provider=el('select');for(const [value,title]of [['mimo-direct','MiMo · 插件内合成'],['volcengine','火山引擎 · 插件内合成'],['azuma','本地 Bert-VITS2 东雪莲'],['mimo','MiMo → 本地 DXL1（需外部服务）']]){const o=el('option',title);o.value=value;provider.append(o);}provider.value=cfg.provider;const providerLabel=el('label','语音引擎 ');providerLabel.append(provider);detail.append(providerLabel);
 const url=input(detail,'本机服务地址',cfg.url,'url'),seed=input(detail,'种子',cfg.seed,'number',0,4294967295,1),fields={},p=profiles(cfg);
 const cloudFields=el('div');detail.append(cloudFields);const creds=cfg.cloud??{};const mimoKey=input(cloudFields,'MiMo API Key',creds.mimoKey??'','password'),volcAppId=input(cloudFields,'火山 App ID',creds.volcAppId??'','text'),volcToken=input(cloudFields,'火山 Access Token',creds.volcToken??'','password'),speaker=input(cloudFields,'火山音色 ID',creds.speaker??'zh_female_vv_uranus_bigtts','text'),resource=input(cloudFields,'火山资源 ID',creds.resource??'seed-tts-2.0','text');for(const f of [mimoKey,volcToken])f.autocomplete='off';cloudFields.append(el('p','凭据随酒馆设置保存，请勿公开包含密钥的设置备份。云端合成无需启动本地试听台。火山请使用语音控制台的 App ID / Access Token。'));
 const ratio=el('select');for(const v of [.5,.75]){const o=el('option',String(v));o.value=v;ratio.append(o);}ratio.value=cfg.ratio;const ratioLabel=el('label','DXL1 索引比例 ');ratioLabel.append(ratio);detail.append(ratioLabel);const voicePrompt=el('textarea');voicePrompt.rows=4;voicePrompt.maxLength=2000;voicePrompt.value=cfg.voicePrompt||BASE_VOICE;voicePrompt.placeholder='留空使用默认成年女性声线';const voiceLabel=el('label','MiMo 基础声线描述 ');voiceLabel.append(voicePrompt);detail.append(voiceLabel,el('p','MiMo 用文字设计声线；火山用音色 ID 选择声线，情绪效果取决于音色支持。云端合成会发送本层正文，DXL1 仅旧本地引擎可用。')); 
 for(const [type,title]of [['dialogue','对话'],['narration','旁白／其他正文']]){const box=el('fieldset');box.append(el('legend',title));fields[type]={speed:input(box,'语速',p[type].speed,'number',.7,speedMax(cfg.provider),.05),volume:input(box,'音量（0～200%）',Math.round(p[type].volume*100),'number',0,200,1),pauseMs:input(box,'段后停顿（毫秒）',p[type].pauseMs,'number',0,5000,50)};const emotion=el('textarea');emotion.rows=2;emotion.maxLength=1000;emotion.placeholder='例如：温柔、稍慢、像安慰朋友一样';emotion.value=p[type].emotion;fields[type].emotion=emotion;const lab=el('label','MiMo 情绪 ');const presets=el('select');presets.setAttribute('aria-label',title+'情绪预设');const custom=el('option','自定义情绪');custom.value='';presets.append(custom);for(const [name,description]of EMOTIONS){const option=el('option',name);option.value=name;option.title=description;presets.append(option);}presets.value=EMOTIONS.some(([name])=>name===emotion.value)?emotion.value:'';presets.onchange=()=>{if(presets.value)emotion.value=presets.value;};emotion.oninput=()=>{presets.value=EMOTIONS.some(([name])=>name===emotion.value)?emotion.value:'';};lab.append(presets,emotion);box.append(lab);fields[type].volcEmotion=input(box,'火山情绪代码（可留空，如 happy）',p[type].volcEmotion??'','text');detail.append(box);}
 detail.append(el('p','MiMo 语速范围 0.7～2.0 倍，其他引擎 0.7～1.3。情绪可选预设，也可直接填写描述；对话与旁白分别保存。'));
 const quotes=el('textarea');quotes.rows=4;quotes.value=cfg.quotes;const qlabel=el('label','对话引号规则（每行一对）');qlabel.style.display='block';qlabel.append(quotes);detail.append(qlabel,el('p','引号内视为对话，其余为旁白。引号不完整时保留为旁白；引用、强调可在下方手动纠正。'));
 const collect=()=>({...cfg,provider:provider.value,cloud:{mimoKey:mimoKey.value.trim(),volcAppId:volcAppId.value.trim(),volcToken:volcToken.value.trim(),speaker:speaker.value.trim(),resource:resource.value.trim()},ratio:Number(ratio.value),voicePrompt:voicePrompt.value,url:url.value,seed:Number(seed.value),range:range.value,quotes:quotes.value,profiles:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,{speed:Number(v.speed.value),volume:Number(v.volume.value)/100,pauseMs:Number(v.pauseMs.value),emotion:v.emotion.value,volcEmotion:v.volcEmotion.value}]))});
 const status=el('p');status.setAttribute('role','status');const player=scopedPlayer(getPlayer(),source),bar=el('div');bar.className='amin-toolbar';const button=(parent,title,fn)=>{const b=el('button',title);b.type='button';b.onclick=fn;parent.append(b);return b;};
 let sections=[],signature='';const preview=el('details');preview.open=true;preview.append(el('summary','分类预览（可修改分类）'));const rows=el('div');preview.append(rows);
 function analyze(){const next=text.value+'\0'+quotes.value;if(next===signature)return;const parsed=classify(text.value,quotes.value);sections=parsed;signature=next;rows.replaceChildren();for(const section of sections){if(!section.text.trim())continue;const row=el('div');row.className='amin-card';const select=el('select');select.setAttribute('aria-label','段落分类');for(const [value,title]of [['dialogue','对话'],['narration','旁白／其他正文']]){const o=el('option',title);o.value=value;select.append(o);}select.value=section.type;select.onchange=()=>section.type=select.value;row.append(select,el('p',section.text));rows.append(row);}}
 text.onchange=quotes.onchange=()=>{try{analyze();}catch(e){status.textContent=e.message;}};
 button(detail,'保存设置',()=>{try{saveSettings(collect());analyze();status.textContent='设置已保存';}catch(e){status.textContent=e.message;}});
 button(detail,'检查配置',async()=>{try{await health(collect());status.textContent=isCloud(collect())?'必填配置完整；点击播放验证实际合成（可能产生费用）':provider.value==='mimo'?'已连接 MiMo → DXL1':'东雪莲服务已连接';}catch(e){status.textContent=e.message;}});
 let launchController=null;
 const localBar=el('div');localBar.className='amin-toolbar';
 const launch=button(localBar,'启动本地服务',async()=>{try{
  const config=collect(),destination=launchTarget(config);launchController?.abort();launchController=new AbortController();const signal=launchController.signal;
  // Dispatch within the click gesture. No credentials or arbitrary commands enter the URI.
  window.open(destination.uri,'_blank','noopener,noreferrer');launch.disabled=true;status.textContent='已请求启动，请允许系统打开启动器，正在等待连接…';
  const h=await waitForService(config,{signal});status.textContent=config.provider==='mimo'&&!h.key_configured?'DXL1 服务已启动；点击“打开本地配置页”填写 MiMo 密钥。':'本地服务已连接，可以播放';
 }catch(e){if(e.name!=='AbortError')status.textContent=e.message;}finally{launch.disabled=false;}});
 button(localBar,'打开本地配置页',()=>{try{window.open(launchTarget(collect()).base,'_blank','noopener,noreferrer');}catch(e){status.textContent=e.message;}});
 detail.append(localBar);
 const play=button(bar,readMessage?'朗读本层':'播放',()=>{try{if(readMessage){const latest=readMessage();if(latest!==rendered){rendered=latest;text.value=latest;}}const config=collect();saveSettings(config);analyze();player.play(sections.map(s=>({...s})),config);}catch(e){status.textContent=e.message;}});play.className='amin-primary';
 const pause=button(bar,'暂停',()=>player.pause()),resume=button(bar,'继续',()=>player.resume()),stop=button(bar,'停止',()=>player.stop());
 root.append(bar,status,detail,preview);const off=player.subscribe(s=>{status.textContent=s.message;pause.disabled=s.phase!=='playing';resume.disabled=s.phase!=='paused';stop.disabled=!['loading','playing','paused','waiting'].includes(s.phase);});
 function reflectProvider(){const cloud=['mimo-direct','volcengine'].includes(provider.value);localBar.hidden=cloud;url.parentElement.hidden=cloud;seed.parentElement.hidden=cloud;ratioLabel.hidden=provider.value!=='mimo';mimoKey.parentElement.hidden=provider.value!=='mimo-direct';for(const f of [volcAppId,volcToken,speaker,resource])f.parentElement.hidden=provider.value!=='volcengine';cloudFields.hidden=!cloud;voiceLabel.hidden=provider.value==='volcengine'||provider.value==='azuma';for(const v of Object.values(fields)){v.speed.max=speedMax(provider.value);v.speed.title='范围 0.7～'+speedMax(provider.value)+'；MiMo 为保持音高的播放倍速';v.emotion.parentElement.hidden=!['mimo-direct','mimo'].includes(provider.value);v.volcEmotion.parentElement.hidden=provider.value!=='volcengine';}}provider.onchange=()=>{launchController?.abort();url.value=provider.value==='mimo'?'http://127.0.0.1:9884':'http://127.0.0.1:9883';reflectProvider();};target.append(root);reflectProvider();analyze();return {dispose(){launchController?.abort();off();root.remove();},open(){}};
}
