const generate=options=>generateActual({sourceOptions:{loadWorldInfo:async()=>({selected_world_info:[]})},...options});
import test from 'node:test';import assert from 'node:assert/strict';
import {generate as generateActual,collectSources,parseAssessment,parseJSON,followPrompt} from '../ai.js';import {harness,sample} from './fixtures.js';import {ROOT} from '../model.js';
test('source capture includes selected full loaded messages and books without silent truncation',async()=>{const {ctx}=harness();ctx.chat=[{mes:'x'.repeat(2000),name:'A'},{is_system:true,mes:'hidden'}];const result=await collectSources(ctx,{includeCharacter:true,includeChat:true,books:'test'},{loadWorldInfo:async()=>({selected_world_info:['test']}),readBook:async()=>({entries:{0:{content:'book'},1:{content:'disabled',disable:true}}})});assert.equal(result.chat[0].text.length,2000);assert.equal(result.worldbooks[0].entries.length,1);assert.equal(result.character.name,'角色');ctx.chat[0].mes='x'.repeat(130000);await assert.rejects(collectSources(ctx,{includeChat:true,readWorldbooks:false}),/超过/);});
test('malformed/truncated JSON and nonexistent assessment subjects are rejected',()=>{assert.throws(()=>parseJSON('{"a":1}{'),/合法/);assert.throws(()=>parseAssessment(JSON.stringify({title:'x',criteria:'x',summary:'x',limitations:'x',rows:[{group:'organizations',id:'missing'}]}),sample()),/不存在/);});
test('button generation uses shared capture, includes request and never writes before confirmation',async()=>{const {api}=harness();let observed;const ai={capture:id=>({app:id}),generate:async(task,ctx,request,opts)=>{observed={task,request,opts};const d=api.read();d.summary='更新';return JSON.stringify(d);}};await generate({api,ai});assert.equal(api.read().summary,'');assert.equal(api.pending().doc.summary,'更新');assert.equal(observed.opts.snapshot.app,'organizations');assert.equal(observed.opts.includeEffects,false);assert.equal(JSON.parse(observed.request.prompt).operation,'update');await api.confirm();assert.equal(api.read().summary,'更新');});
test('delayed AI return after chat switch cannot create preview in another chat',async()=>{const h=harness();let release;const promise=new Promise(r=>release=r),ai={capture:()=>({}),generate:()=>promise};const running=generate({api:h.api,ai});await new Promise(r=>setImmediate(r));h.switchChat();release(JSON.stringify(sample()));await assert.rejects(running,/变化|取消/);assert.equal(h.api.pending(),null);});
test('cancelled request cannot create a late preview even if transport ignores abort',async()=>{const {api}=harness();let release;const p=new Promise(r=>release=r),ai={capture:()=>({}),generate:()=>p};const work=generate({api,ai});await new Promise(r=>setImmediate(r));api.cancel();release(JSON.stringify(sample()));await assert.rejects(work,/取消/);assert.equal(api.pending(),null);});
test('follow protocol uses separate root, disabled state and lock paths, not old battle blocks',()=>{const text=followPrompt({follow:false,allowNew:false,updateEnabled:true,updateRules:'人口不明不猜测'},['organizations.a.name']);assert.ok(text.includes('{{xbgetvar_yaml_idx::'+ROOT+'}}'));assert.match(text,/已关闭/);assert.match(text,/organizations.a.name/);assert.ok(!text.includes('FACTION_UPDATE'));assert.match(text,/人口不明不猜测/);});
