import test from 'node:test';import assert from 'node:assert/strict';
import {empty,entity,validate,clone,mergeProposal,deleteEntity,enforceLocks,rankMetrics} from '../model.js';
export function sample(){const d=empty();d.name='澜湾';d.organizations.a=entity('organizations','共和国');d.organizations.b=entity('organizations','商会');d.alliances.c=entity('alliances','合作议会');d.alliances.c.members=[{organization:'a',role:'成员',note:''},{organization:'b',role:'成员',note:''}];d.regions.r=entity('regions','南港');d.regions.r.controllers=[{organization:'a',role:'名义归属',note:''},{organization:'b',role:'经营',note:''}];d.regions.r.population='18万';return d;}
test('three entity kinds validate without guessed metrics and references are distinct',()=>{const d=validate(sample());assert.deepEqual(d.organizations.a.metrics,[]);assert.equal(d.regions.r.controllers.length,2);assert.equal(d.organizations.a.certainty,'未明确');});
test('invalid references, duplicate IDs and region cycles fail rather than silently repair',()=>{let d=sample();d.regions.r.controllers[0].organization='missing';assert.throws(()=>validate(d),/关联/);d=sample();d.regions.a=entity('regions','重复ID');assert.throws(()=>validate(d),/重复/);d=sample();d.regions.s=entity('regions','上级');d.regions.r.parent='s';d.regions.s.parent='r';assert.throws(()=>validate(d),/循环/);});
test('typed metrics reject fake unknown values, bad ranges and nonfinite numbers',()=>{for(const m of [{kind:'unknown',value:50},{kind:'range',value:[20,10]},{kind:'number',value:NaN}]){const d=sample();d.organizations.a.metrics=[{key:'pop',label:'人口',unit:'人',source:'',...m}];assert.throws(()=>validate(d));}});
test('locked fields cannot be deleted or changed by update/replace',()=>{const d=sample(),p=clone(d);p.organizations.a.ideology='新思潮';assert.throws(()=>mergeProposal(d,p,{locks:['organizations.a.ideology']}),/锁定/);delete p.organizations.a;p.alliances.c.members=[];p.regions.r.controllers=[];assert.throws(()=>mergeProposal(d,p,{mode:'replace',locks:['organizations.a.name']}),/锁定/);});
test('fill preserves existing facts and update only adds entities with permission',()=>{const d=sample();d.organizations.a.status='原值';const p=clone(d);p.organizations.a.status='新值';p.organizations.a.ideology='补充';p.organizations.z=entity('organizations','新组织');const f=mergeProposal(d,p,{mode:'fill'});assert.equal(f.organizations.a.status,'原值');assert.equal(f.organizations.a.ideology,'补充');assert.throws(()=>mergeProposal(d,p),/未允许/);assert.ok(mergeProposal(d,p,{allowNew:true}).organizations.z);});
test('single entity update leaves other entities and overview unchanged',()=>{const d=sample(),p=clone(d);p.summary='不应改';p.organizations.a.status='可改';p.organizations.b.status='不可改';const next=mergeProposal(d,p,{target:{group:'organizations',id:'a'}});assert.equal(next.summary,'');assert.equal(next.organizations.a.status,'可改');assert.equal(next.organizations.b.status,'');});
test('peaceful ownership update never changes population or invents damage',()=>{const d=sample(),p=clone(d);p.regions.r.controllers=[{organization:'b',role:'管理',note:'和平移交'}];const next=mergeProposal(d,p);assert.equal(next.regions.r.population,'18万');assert.equal(next.regions.r.status,'');});
test('deletion clears only referencing links and parent relation',()=>{const d=sample(),next=deleteEntity(d,'organizations','a');assert.equal(next.alliances.c.members.length,1);assert.equal(next.regions.r.controllers.length,1);assert.ok(d.organizations.a);});
test('metric ranking separates units, unknowns and ranges, permits ties',()=>{const d=sample();d.organizations.z=entity('organizations','第三');for(const [id,unit,value]of [['a','人',100],['b','人',100],['z','万人',2]])d.organizations[id].metrics=[{key:'pop',label:'人口',kind:'number',unit,value,source:''}];const r=rankMetrics(d,{key:'pop',unit:'人'});assert.deepEqual(r.included.map(x=>x.rank),[1,1]);assert.equal(r.excluded[0].id,'z');});
