import test from 'node:test';import assert from 'node:assert/strict';
import {collectSources,generate} from '../ai.js';import {worldbookChoices,freshWorldbook} from '../sources.js';import {harness} from './fixtures.js';
function setup(){const h=harness();h.ctx.characters[0].data.extensions={world:'bound'};h.ctx.chatMetadata.world_info='chat';const wi={selected_world_info:['global','bound'],world_info:{charLore:[{name:'a',extraBooks:['extra']}]},world_names:['global','bound','extra','chat','not-enabled']};let revision='first';const calls=[];return {...h,wi,calls,setRevision:v=>revision=v,options:{loadWorldInfo:async()=>wi,readBook:async name=>{calls.push(name);return {entries:{one:{content:name+':'+revision,key:['NEVER_MATCH'],constant:false,probability:0,useProbability:true},two:{content:'disabled',disable:true},three:{content:'off',enabled:false},four:{content:'always',constant:true}}};}}};}
test('read-worldbooks defaults on and enabled catalog is not the entire library',async()=>{const h=setup();assert.equal(h.api.config().readWorldbooks,true);const list=await worldbookChoices(h.ctx,h.options);assert.deepEqual(new Set(list.map(b=>b.name)),new Set(['global','bound','extra','chat']));assert.equal(list.find(b=>b.name==='bound').automatic,true);assert.equal(list.find(b=>b.name==='extra').automatic,true);});
test('character sources automatically include bound and extra books; selected duplicates read once',async()=>{const h=setup();const r=await collectSources(h.ctx,{includeCharacter:true,selectedBooks:['bound','global']},h.options);assert.equal(r.character.name,'角色');assert.deepEqual(new Set(h.calls),new Set(['global','bound','extra']));assert.equal(h.calls.length,3);assert.ok(r.worldbooks.every(b=>b.entries.length===2));assert.ok(r.worldbooks[0].entries.some(e=>e.content.includes('first')));});
test('worldbook master switch overrides character bindings and manual selection without calling loader',async()=>{const h=setup();const r=await collectSources(h.ctx,{includeCharacter:true,includeChat:true,readWorldbooks:false,selectedBooks:['global']},{loadWorldInfo:()=>{throw Error('must not load');}});assert.equal(r.character.name,'角色');assert.ok(r.chat.length);assert.deepEqual(r.worldbooks,[]);});
test('manual selection still works with character reading off; legacy names migrate through enabled catalog',async()=>{const h=setup();await collectSources(h.ctx,{includeCharacter:false,books:'global\nglobal'},h.options);assert.deepEqual(h.calls,['global']);});
test('inactive saved choices and missing enabled-list interfaces fail explicitly',async()=>{const h=setup();await assert.rejects(collectSources(h.ctx,{selectedBooks:['not-enabled']},h.options),/当前未启用/);await assert.rejects(worldbookChoices(h.ctx,{loadWorldInfo:async()=>({world_names:['all']})}),/未提供/);});
test('replace/update/fill/assessment each reread latest contents before each AI request',async()=>{for(const mode of ['replace','update','fill','assessment']){const h=setup(),requests=[];const ai={capture:()=>({}),generate:async(task,ctx,request)=>{requests.push(JSON.parse(request.prompt));return mode==='assessment'?JSON.stringify({title:'t',criteria:'c',summary:'s',limitations:'l',rows:[]}):JSON.stringify(h.api.read());}};await generate({api:h.api,ai,mode,sourceOptions:h.options});h.api.discard();h.setRevision('second');await generate({api:h.api,ai,mode,sourceOptions:h.options});assert.ok(requests[0].sources.worldbooks[0].entries[0].content.endsWith('first'));assert.ok(requests[1].sources.worldbooks[0].entries[0].content.endsWith('second'));assert.equal(h.calls.length,4);}});
test('latest bindings are resolved anew and never reused from a previous generation',async()=>{const h=setup();await collectSources(h.ctx,{includeCharacter:true},h.options);h.ctx.characters[0].data.extensions.world='new-bound';h.calls.length=0;await collectSources(h.ctx,{includeCharacter:true},h.options);assert.ok(h.calls.includes('new-bound'));assert.ok(!h.calls.includes('bound'));});
test('fresh HTTP reads bypass cached loadWorldInfo and use no-store for every request',async()=>{const h=setup();h.ctx.getRequestHeaders=()=>({'x-fixture':'yes'});let n=0;const options={fetcher:async(route,opt)=>{assert.equal(route,'/api/worldinfo/get');assert.equal(opt.cache,'no-store');assert.deepEqual(JSON.parse(opt.body),{name:'bound'});return {ok:true,json:async()=>({entries:{one:{content:String(++n)}}})};}};assert.equal((await freshWorldbook(h.ctx,'bound',options)).entries.one.content,'1');assert.equal((await freshWorldbook(h.ctx,'bound',options)).entries.one.content,'2');});
test('failed fresh read or changed chat cannot submit a model request',async()=>{const h=setup();h.ctx.getRequestHeaders=()=>({});await assert.rejects(freshWorldbook(h.ctx,'bound',{fetcher:async()=>({ok:false})}),/无法重新读取/);let release,models=0;const waiting=new Promise(r=>release=r);const work=generate({api:h.api,ai:{capture:()=>({}),generate:async()=>{models++;}},sourceOptions:{...h.options,readBook:async()=>{await waiting;return {entries:{}};}}});await new Promise(r=>setImmediate(r));h.switchChat();release();await assert.rejects(work,/变化|取消/);assert.equal(models,0);});
test('group catalogs list members for manual selection without automatic single-speaker binding',async()=>{const h=setup();h.ctx.groupId='g';h.ctx.groups=[{id:'g',members:['a.png']}];const list=await worldbookChoices(h.ctx,h.options);assert.ok(list.some(b=>b.name==='bound'));assert.ok(list.every(b=>!b.automatic));await collectSources(h.ctx,{includeCharacter:true},h.options);assert.equal(h.calls.length,0);});
test('worldbook toggle and selected names persist without changing the default for another role',async()=>{const h=setup();await h.api.saveConfig({...h.api.config(),readWorldbooks:false,selectedBooks:['global']});assert.equal(h.api.config().readWorldbooks,false);assert.deepEqual(h.api.config().selectedBooks,['global']);h.ctx.characters.push({avatar:'other.png'});h.ctx.characterId=1;assert.equal(h.api.config().readWorldbooks,true);});
