import {harness} from '../test/fixtures.js';
import {initializeAI} from '../../../ai/service.js';
import {createDemoDocument} from '../../map/src/core/demo.js';
const ensure=(v,m)=>{if(!v)throw Error(m);};
const wait=async(fn,label)=>{for(let i=0;i<250;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timeout: '+label);};
export async function runUnifiedSourceBrowserChecks(){
 const h=harness(),ctx=h.ctx;h.api.dispose();ctx.characters[0].name='测试角色';ctx.characters[0].data.extensions={world:'bound'};ctx.characters[0].data.description='CARD_SOURCE_MARKER';ctx.extensionSettings.dynamicMapNamespace='unified-source-fixture';ctx.chatMetadata.variables.状态栏=JSON.stringify({版本:1,项目:{世界:{地点:'旧地点'}}});ctx.getRequestHeaders=()=>({});window.SillyTavern={getContext:()=>ctx};window.confirm=()=>true;
 const nativeFetch=window.fetch.bind(window),reads=[],requests=[];let revision='FIRST',kind='map',stateSequence=0,typeChange=false;
 window.fetch=async(url,options={})=>{if(String(url)==='/api/worldinfo/get'){const name=JSON.parse(options.body).name;ensure(options.cache==='no-store','must bypass cache');reads.push({name,revision});return new Response(JSON.stringify({entries:{one:{content:name+'_'+revision,key:['never_matches'],probability:0,constant:false},off:{content:'DISABLED_MARKER',disable:true}}}),{status:200,headers:{'Content-Type':'application/json'}});}return nativeFetch(url,options);};
 ctx.generateRaw=async request=>{requests.push({kind,request});if(kind==='map')return JSON.stringify(request.systemPrompt.includes('本次为新增模式')?{nodes:{},edges:[]}:createDemoDocument());return JSON.stringify({版本:1,项目:{世界:{地点:typeChange?42:'状态地点'+(++stateSequence)}}});};
 initializeAI(localStorage,'unified-source-fixture',{resolveConnection:async config=>config});
 for(const href of ['/apps/map/style.css','/apps/status/style.css'])await new Promise((resolve,reject)=>{const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.onload=resolve;link.onerror=reject;document.head.append(link);});
 const root=document.getElementById('app'),mapHost=document.createElement('div');root.append(mapHost);
 const {initialize:initializeMap}=await import('/apps/map/index.js');const map=initializeMap({mount:mapHost});
 const click=(host,text)=>{const b=[...host.querySelectorAll('button')].find(b=>b.textContent===text);ensure(b,'button '+text);b.click();};
 const change=(input,value)=>{ensure(input,'missing input');input.checked=value;input.dispatchEvent(new Event('change',{bubbles:true}));};
 const {mountWorldbookSources}=await import('/apps/worldbook-source-ui.js');let release;const delayedHost=document.createElement('div');root.append(delayedHost);const delayedCtx={...ctx,chatMetadata:{world_info:'chatbook'}};
 const delayed=mountWorldbookSources(delayedHost,{context:()=>delayedCtx,value:{legacyBindings:true,includeGlobalBooks:true,extraBooks:'extra'},sourceOptions:{loadWorldInfo:()=>new Promise(resolve=>release=resolve)}});
 const waiting=delayedHost.querySelector('[data-worldbook=extra]');ensure(waiting.disabled,'old selections disabled until migration catalogue arrives');change(waiting,false);ensure(!Array.isArray(delayed.getValue().selectedBooks),'pending edit cannot finalize migration');
 release({selected_world_info:['global','extra'],world_info:{}});await wait(()=>delayedHost.querySelector('[data-worldbook=global]'),'delayed catalogue');change(delayedHost.querySelector('[data-worldbook=extra]'),false);ensure(delayed.getValue().selectedBooks.includes('global')&&delayed.getValue().selectedBooks.includes('chatbook'),'migration preserves global and chat choices after delayed edit');ensure(!delayed.getValue().selectedBooks.includes('extra'),'extra can be deselected after migration');delayed.dispose();delayedHost.remove();
 mapHost.querySelector('[data-tab=ai]').click();await wait(()=>mapHost.querySelector('[data-worldbook=global]'),'map choices');
 ensure(mapHost.querySelector('[aria-label="是否读取世界书"]').checked,'map default on');ensure(!mapHost.querySelector('[data-worldbook=bound]').checked&&!mapHost.querySelector('[data-worldbook=bound]').disabled,'map bound is an optional selection');ensure(!mapHost.querySelector('[data-worldbook=inactive]'),'only enabled book list');
 change(mapHost.querySelector('[data-worldbook=global]'),true);
 async function mapAction(label){const n=requests.length;click(mapHost,label);await wait(()=>requests.length>n&&!mapHost.textContent.includes('正在生成…'),'map generation '+mapHost.textContent);const request=requests.at(-1).request;ensure(!JSON.stringify(request).includes('DISABLED_MARKER'),'disabled content excluded');return request;}
 let request=await mapAction('生成地图草稿');ensure(request.prompt.includes('global_FIRST')&&!request.prompt.includes('bound_FIRST')&&request.prompt.includes('CARD_SOURCE_MARKER'),'map card does not imply bound books');
 change(mapHost.querySelector('[data-worldbook=bound]'),true);request=await mapAction('生成地图草稿');ensure(request.prompt.includes('bound_FIRST'),'explicit bound selection is read');change(mapHost.querySelector('[data-worldbook=bound]'),false);
 revision='SECOND';request=await mapAction('根据资料与聊天记录新增地点和道路');ensure(request.prompt.includes('global_SECOND')&&!request.prompt.includes('global_FIRST')&&!request.prompt.includes('bound_SECOND'),'map expansion honors deselection and rereads');
 change(mapHost.querySelector('[data-worldbook=bound]'),true);change(mapHost.querySelector('[aria-label="读取当前角色设定"]'),false);request=await mapAction('生成地图草稿');ensure(request.prompt.includes('bound_SECOND')&&!request.prompt.includes('CARD_SOURCE_MARKER'),'map reads selected book without character');change(mapHost.querySelector('[aria-label="读取当前角色设定"]'),true);change(mapHost.querySelector('[data-worldbook=bound]'),false);
 change(mapHost.querySelector('[aria-label="是否读取世界书"]'),false);const previousReads=reads.length;request=await mapAction('生成地图草稿');ensure(reads.length===previousReads,'map disabled does not fetch bodies');ensure(request.prompt.includes('CARD_SOURCE_MARKER')&&!request.prompt.includes('global_SECOND'),'map still sends card when worlds off');
 map.destroy();const reopened=initializeMap({mount:mapHost});mapHost.querySelector('[data-tab=ai]').click();await wait(()=>mapHost.querySelector('[data-worldbook=global]'),'map choices on reopen');ensure(!mapHost.querySelector('[aria-label="是否读取世界书"]').checked,'map setting persists');ensure(mapHost.querySelector('[data-worldbook=global]').checked,'map selection preserved');reopened.destroy();mapHost.remove();
 kind='status';const statusHost=document.createElement('div');root.append(statusHost);const {initialize:initializeStatus}=await import('/apps/status/index.js');const status=initializeStatus({mount:statusHost});await status.open();click(statusHost,'生成设置');await wait(()=>statusHost.querySelector('[data-worldbook=global]'),'status choices');const form=statusHost.querySelector('.wsh-generation-form');
 ensure(form.querySelector('[aria-label="是否读取世界书"]').checked,'status default independently on');ensure(form.querySelector('[data-worldbook=global]').checked,'legacy enabled global option migrated');ensure(!form.querySelector('[data-worldbook=bound]').disabled,'status bound can be deselected');ensure(!form.textContent.includes('设定字符上限'),'retired cap control absent');
 async function statusAction(label){const n=requests.length;click(form,label);await wait(()=>requests.length>n&&!form.querySelector('button.amin-primary:disabled'),'status generation '+form.textContent);return requests.at(-1).request;}
 const field=label=>[...form.querySelectorAll('label')].find(l=>l.textContent.includes(label));
 field('状态栏要求').querySelector('textarea').value='FRESH_STATUS_INSTRUCTIONS';field('当前情况补充').querySelector('textarea').value='FRESH_UPDATE_NOTE';
 change(form.querySelector('[data-worldbook=bound]'),false);change(form.querySelector('[data-worldbook=global]'),false);const beforeCardOnly=reads.length;request=await statusAction('生成／补充');ensure(reads.length===beforeCardOnly&&request.prompt.includes('CARD_SOURCE_MARKER'),'status card with no selected books reads no worlds');change(form.querySelector('[data-worldbook=bound]'),true);change(form.querySelector('[data-worldbook=global]'),true);
 revision='STATUS_ONE';request=await statusAction('生成／补充');ensure(request.prompt.includes('FRESH_STATUS_INSTRUCTIONS')&&request.prompt.includes('FRESH_UPDATE_NOTE'),'source choices cannot overwrite current form inputs');ensure(request.prompt.includes('global_STATUS_ONE')&&request.prompt.includes('bound_STATUS_ONE'),'status sources captured');
 change(form.querySelector('[data-worldbook=bound]'),false);revision='STATUS_TWO';request=await statusAction('重新生成整套');ensure(request.prompt.includes('global_STATUS_TWO')&&!request.prompt.includes('global_STATUS_ONE')&&!request.prompt.includes('bound_STATUS_TWO'),'status replace honors deselection and rereads');change(form.querySelector('[data-worldbook=bound]'),true);
 revision='STATUS_THREE';request=await statusAction('按当前剧情更新值');ensure(request.prompt.includes('bound_STATUS_THREE'),'status update rereads');
 change(form.querySelector('[aria-label="是否读取世界书"]'),false);const noRead=reads.length;request=await statusAction('按当前剧情更新值');ensure(reads.length===noRead,'status worlds off does not fetch');ensure(request.prompt.includes('CARD_SOURCE_MARKER')&&!request.prompt.includes('STATUS_THREE'),'status keeps card not books');
 const saved=ctx.extensionSettings.amin_os_worldbook_sources_v1;ensure(saved.status['character:a.png'].readWorldbooks===false&&saved.map['character:a.png'].readWorldbooks===false,'separate application preferences persisted');
 const roleCheckbox=form.querySelector('[aria-label="读取当前角色设定"]');change(roleCheckbox,false);request=await statusAction('按当前剧情更新值');ensure(!request.prompt.includes('CARD_SOURCE_MARKER'),'card can be independently disabled');
 change(form.querySelector('[aria-label="是否读取世界书"]'),true);request=await statusAction('按当前剧情更新值');ensure(request.prompt.includes('bound_STATUS_THREE')&&!request.prompt.includes('CARD_SOURCE_MARKER'),'status reads selected book without character');change(form.querySelector('[aria-label="是否读取世界书"]'),false);
 typeChange=true;change(field('允许更改已有字段类型').querySelector('input'),true);await statusAction('按当前剧情更新值');ensure(JSON.parse(ctx.chatMetadata.variables.状态栏).项目.世界.地点===42,'type-change authorization must survive source controls');
 const originalRole=ctx.characters[0].avatar;ctx.characters[0].avatar='other.png';const {sourceSettings}=await import('/apps/worldbook-sources.js');ensure(sourceSettings(ctx,'status').readWorldbooks===true&&sourceSettings(ctx,'map').readWorldbooks===true,'other role retains defaults');ctx.characters[0].avatar=originalRole;
 window.fetch=nativeFetch;return 'PASS real map/status UI: selected worlds, independently selectable bound books, per-operation fresh bodies, default/disabled switches, role/app persistence and unchanged generation paths';
}
